name: Daily Job Market Tracker

on:
  schedule:
    - cron: '0 0 * * *' # Runs at Midnight UTC
  workflow_dispatch:      # Allows manual testing

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        # Added pandas and matplotlib here
        run: |
          pip install requests pandas matplotlib plotly

      - name: Run tracking script
        env:
          ADZUNA_APP_ID: ${{ secrets.ADZUNA_APP_ID }}
          ADZUNA_APP_KEY: ${{ secrets.ADZUNA_APP_KEY }}
        run: python daily_tracker.py

      - name: Generate Trend Graph
        # This runs the new script to create the PNG
        run: python plot_trends.py

      - name: Commit and Push Data
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Add the CSV, the PNG, AND the new HTML file
          git add job_market_history.csv job_market_trends.png index.html
          
          # Commit and push
          git commit -m "Update daily stats and dashboard" || exit 0
          git push